title: $blog
author:
  name: melwitt
description: > # this means to ignore newlines until "show_excerpts:"
  A place to share things that will hopefully help others.

show_excerpts: true # set to true to show excerpts on the homepage

google_site_verification: 7GJG2CqUDb3q0oaH9mpwNtU7QHomFAj80wVhd1SpEdM

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: solarized

  # generate social links in footer
  social_links:
    # twitter: jekyll
    github: melwitt
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: melwitt
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    # google_scholar_id: qc6CJjYAAAAJ

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: minima
remote_theme: jekyll/minima@41b97699af658128fa9983e5312ca5516641f335

plugins:
 - jekyll-remote-theme
 - jekyll-seo-tag
 - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
